$ErrorActionPreference = "Stop"

# 1. First, run the screener to get the latest candidates
Write-Host "Running mm-screener to find top candidates..."
go run ./cmd/mm-screener/mm-screener -top 5

# 2. Find the newest JSON file generated by mm-screener
$screenerDir = "data\mm_screener"
$latestJson = Get-ChildItem -Path $screenerDir -Filter "*.json" | Sort-Object LastWriteTime -Descending | Select-Object -First 1

if (-not $latestJson) {
    Write-Host "No screener output found in $screenerDir."
    exit
}

Write-Host "Reading candidates from $($latestJson.Name)..."
$data = Get-Content $latestJson.FullName | ConvertFrom-Json

# 3. Parallelize the surveys
# We use 9 minutes duration and 4 seconds interval to stay under 10 minutes 
# and not trigger Indodax 180 req/min limits across 5 pairs.
$duration = "9m"
$interval = "4s"

# Limit to top 5 survivors
$survivors = $data.rows | Where-Object { $_.passed -eq $true } | Select-Object -First 5

Write-Host "Starting parallel surveys for $($survivors.Count) pairs. Duration: $duration, Interval: $interval"

foreach ($row in $survivors) {
    $pair = $row.pair
    Write-Host " -> Spawning background process for $pair..."
    
    # Start-Process runs the command asynchronously in the background.
    # This is how Claude Opus parallelized it! It doesn't wait for the command to finish.
    Start-Process -NoNewWindow -FilePath "go" -ArgumentList "run ./cmd/mm-survey/mm-survey -pair $pair -duration $duration -interval $interval"
}

Write-Host "`nAll survey processes have been launched in the background!"
Write-Host "They will run simultaneously for $duration."
Write-Host "You can check the results in 'data\mm_survey' when they finish."
